# Generated by Django 3.0.4 on 2020-06-28 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_auto_20200131_0131'),
        ('todo', '0002_auto_20200314_0915'),
    ]

    operations = [
    ]
